// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.

export const WORKER_COMMANDS = [
  "init",
  "loadAssets",
  "setState",
  "evaluate",
  "applyPreset",
  "runSweep",
  "dispose"
];

export const WORKER_EVENTS = [
  "ready",
  "assetsLoaded",
  "stateUpdated",
  "evaluation",
  "presetApplied",
  "sweepProgress",
  "diagnostic",
  "error"
];

export const COMMAND_FIELDS = {
  "init": {
    "category": "lifecycle",
    "required": [],
    "optional": [
      "runtimeConfig"
    ]
  },
  "loadAssets": {
    "category": "asset_loading",
    "required": [
      "assetConfig"
    ],
    "optional": []
  },
  "setState": {
    "category": "state_update",
    "required": [
      "statePatch"
    ],
    "optional": []
  },
  "evaluate": {
    "category": "evaluation",
    "required": [],
    "optional": [
      "compareMode"
    ]
  },
  "applyPreset": {
    "category": "presets",
    "required": [
      "presetId"
    ],
    "optional": []
  },
  "runSweep": {
    "category": "presets",
    "required": [
      "sweepId"
    ],
    "optional": []
  },
  "dispose": {
    "category": "lifecycle",
    "required": [],
    "optional": []
  },
};

export const EVENT_FIELDS = {
  "ready": {
    "category": "lifecycle",
    "required": [],
    "optional": [
      "contractVersion",
      "capabilities"
    ]
  },
  "assetsLoaded": {
    "category": "asset_loading",
    "required": [
      "bundleId"
    ],
    "optional": [
      "manifestUrl",
      "assetBaseUrl",
      "parameterCount"
    ]
  },
  "stateUpdated": {
    "category": "state_update",
    "required": [
      "revision",
      "state"
    ],
    "optional": []
  },
  "evaluation": {
    "category": "evaluation",
    "required": [
      "evaluation"
    ],
    "optional": []
  },
  "presetApplied": {
    "category": "presets",
    "required": [
      "presetId"
    ],
    "optional": [
      "revision"
    ]
  },
  "sweepProgress": {
    "category": "presets",
    "required": [
      "sweepId",
      "phase"
    ],
    "optional": [
      "revision"
    ]
  },
  "diagnostic": {
    "category": "diagnostics",
    "required": [
      "level",
      "message"
    ],
    "optional": []
  },
  "error": {
    "category": "diagnostics",
    "required": [
      "code",
      "message"
    ],
    "optional": []
  },
};
