#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path

from build_github_pages import (
    PLAY_ALLOWLIST,
    apply_play_host_tuning,
    build_landing_html,
    build_viewer_html,
    copy_path,
    load_manifest,
    normalize_supported_lods,
    remove_path,
    write_text,
)


def write_deploy_site_config(
    path: Path,
    *,
    play_ver: str,
    forge_base_template: str,
    mhr_lod: int,
    manifest_url: str,
    asset_base_url: str,
    env_asset_base: str,
) -> None:
    content = f"""// Auto-generated by tools/build_site_app.py.
// This file is the stable deployment contract for MHR Play site mounting.
globalThis.PLAY_VER = {json.dumps(play_ver)};
globalThis.__FORGE_DIST_BASE__ = {json.dumps(forge_base_template)};
globalThis.PLAY_MHR_LOD = {json.dumps(int(mhr_lod))};
globalThis.PLAY_MHR_MANIFEST_URL = {json.dumps(manifest_url)};
globalThis.PLAY_MHR_ASSET_BASE_URL = {json.dumps(asset_base_url)};
"""
    if env_asset_base.strip():
        content += f"globalThis.PLAY_ENV_ASSET_BASE = {json.dumps(env_asset_base)};\n"
    else:
        content += "// globalThis.PLAY_ENV_ASSET_BASE = 'https://assets.example.com/env/';\n"
    write_text(path, content)


def remove_heavy_assets(viewer_root: Path) -> None:
    remove_path(viewer_root / "assets" / "env")
    remove_path(viewer_root / "mhr-official")


def pack_zip(source_root: Path, zip_path: Path) -> None:
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = zip_path.with_suffix(zip_path.suffix + ".tmp")
    remove_path(temp_path)
    with zipfile.ZipFile(temp_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for item in sorted(source_root.rglob("*")):
            if not item.is_file():
                continue
            archive.write(item, arcname=item.relative_to(source_root).as_posix())
    temp_path.replace(zip_path)


def build_site_app(
    *,
    play_src: Path,
    out_root: Path,
    viewer_path: str,
    default_lod: int,
    supported_lods: list[int],
    play_ver: str,
    forge_base_template: str,
    mhr_lod: int,
    mhr_manifest_url: str,
    mhr_asset_base_url: str,
    env_asset_base: str,
) -> None:
    viewer_root = out_root / viewer_path
    remove_path(out_root)
    viewer_root.mkdir(parents=True, exist_ok=True)

    for rel in PLAY_ALLOWLIST:
        copy_path(play_src / rel, viewer_root / rel)

    apply_play_host_tuning(viewer_root)
    remove_heavy_assets(viewer_root)

    copy_path(Path("mjwp_inject/site/mhr.css"), viewer_root / "mhr.css")
    copy_path(Path("mjwp_inject/site/model/mhr_stage.xml"), viewer_root / "model" / "mhr_stage.xml")
    copy_path(Path("mjwp_inject/plugin/plugins/mhr_profile_plugin.mjs"), viewer_root / "plugins" / "mhr_profile_plugin.mjs")
    copy_path(Path("mjwp_inject/plugin/profiles/mhr"), viewer_root / "profiles" / "mhr")

    write_deploy_site_config(
        viewer_root / "site_config.js",
        play_ver=play_ver,
        forge_base_template=forge_base_template,
        mhr_lod=mhr_lod,
        manifest_url=mhr_manifest_url,
        asset_base_url=mhr_asset_base_url,
        env_asset_base=env_asset_base,
    )

    viewer_html = build_viewer_html(
        default_lod,
        supported_lods,
        fallback_manifest_template=None,
        fallback_asset_base_template=None,
        storage_namespace="mhr-site-app",
        built_in_default_open=False,
    )
    write_text(viewer_root / "index.html", viewer_html)
    write_text(viewer_root / "mhr.html", viewer_html)
    write_text(out_root / "index.html", build_landing_html(None, supported_lods, viewer_path))


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a deploy-oriented MHR Play app artifact with externalized heavy assets.")
    parser.add_argument("--play-src", type=Path, required=True, help="Path to a mujoco-wasm-play checkout.")
    parser.add_argument("--out", type=Path, required=True, help="Output directory for the deploy-oriented app artifact.")
    parser.add_argument("--manifest", type=Path, default=Path("release/site_manifest.json"), help="Site manifest with Play/runtime defaults.")
    parser.add_argument("--mhr-manifest-url", required=True, help="External manifest URL for the default MHR LoD.")
    parser.add_argument("--mhr-asset-base-url", required=True, help="External base URL for the default MHR LoD asset chunks.")
    parser.add_argument("--env-asset-base", default="", help="Optional external base URL for Play environment HDRI/EXR assets.")
    parser.add_argument("--mhr-lod", type=int, default=None, help="Default MHR LoD written into site_config.js.")
    parser.add_argument("--zip-out", type=Path, default=None, help="Optional zip output path for the built app artifact.")
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    play = manifest.get("play", {})
    forge = manifest.get("forge", {})
    pages = manifest.get("pages", {})

    play_ver = str(play.get("ver", "")).strip()
    forge_base_template = str(forge.get("baseTemplate", "")).strip()
    viewer_path = str(pages.get("viewerPath", "viewer")).strip().strip("/")
    default_lod = int(pages.get("defaultLod", 1))
    supported_lods = normalize_supported_lods(pages.get("supportedLods"), default_lod)
    mhr_lod = int(args.mhr_lod) if args.mhr_lod is not None else default_lod

    if not play_ver:
        raise ValueError("release/site_manifest.json must set play.ver")
    if not forge_base_template:
        raise ValueError("release/site_manifest.json must set forge.baseTemplate")
    if not viewer_path:
        raise ValueError("release/site_manifest.json must set a non-empty pages.viewerPath")
    if mhr_lod not in supported_lods:
        raise ValueError(f"--mhr-lod must be one of {supported_lods}, got {mhr_lod}")

    play_src = args.play_src.expanduser().resolve()
    out_root = args.out.expanduser().resolve()
    if not play_src.exists():
        raise FileNotFoundError(f"Play source checkout not found: {play_src}")

    build_site_app(
        play_src=play_src,
        out_root=out_root,
        viewer_path=viewer_path,
        default_lod=default_lod,
        supported_lods=supported_lods,
        play_ver=play_ver,
        forge_base_template=forge_base_template,
        mhr_lod=mhr_lod,
        mhr_manifest_url=args.mhr_manifest_url.strip(),
        mhr_asset_base_url=args.mhr_asset_base_url.strip(),
        env_asset_base=args.env_asset_base.strip(),
    )

    if args.zip_out is not None:
        pack_zip(out_root, args.zip_out.expanduser().resolve())

    print(f"Built deploy-oriented MHR Play app -> {out_root}")
    if args.zip_out is not None:
        print(f"Packed deploy-oriented MHR Play app -> {args.zip_out.expanduser().resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
