import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const specPath = path.join(repoRoot, 'tools', 'worker_protocol.json');
const outDir = path.join(repoRoot, 'worker');
const protocolOutPath = path.join(outDir, 'protocol.gen.mjs');
const dispatchOutPath = path.join(outDir, 'dispatch.gen.mjs');

function normalizeMessageSpec(value, label) {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array.`);
  }
  return value.map((entry, index) => {
    if (!entry || typeof entry !== 'object') {
      throw new Error(`${label}[${index}] must be an object.`);
    }
    const name = String(entry.name || '').trim();
    if (!name) {
      throw new Error(`${label}[${index}] requires name.`);
    }
    const category = String(entry.category || 'uncategorized').trim();
    const required = Array.isArray(entry.required) ? entry.required.map((key) => String(key)) : [];
    const optional = Array.isArray(entry.optional) ? entry.optional.map((key) => String(key)) : [];
    return {
      name,
      category,
      required,
      optional,
    };
  });
}

function renderFieldSpec(name, entries) {
  const rows = entries.map((entry) => {
    const value = JSON.stringify(
      {
        category: entry.category,
        required: entry.required,
        optional: entry.optional,
      },
      null,
      2,
    ).replaceAll('\n', '\n  ');
    return `  ${JSON.stringify(entry.name)}: ${value},`;
  });
  return `export const ${name} = {\n${rows.join('\n')}\n};\n`;
}

const spec = JSON.parse(await readFile(specPath, 'utf8'));
const commandSpec = normalizeMessageSpec(spec.commands, 'commands');
const eventSpec = normalizeMessageSpec(spec.events, 'events');

const protocolOutput = [
  '// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.',
  '',
  `export const WORKER_COMMANDS = ${JSON.stringify(commandSpec.map((entry) => entry.name), null, 2)};\n`,
  `export const WORKER_EVENTS = ${JSON.stringify(eventSpec.map((entry) => entry.name), null, 2)};\n`,
  renderFieldSpec('COMMAND_FIELDS', commandSpec),
  renderFieldSpec('EVENT_FIELDS', eventSpec),
].join('\n');

const dispatchOutput = [
  '// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.',
  '',
  "import { COMMAND_FIELDS, EVENT_FIELDS, WORKER_COMMANDS, WORKER_EVENTS } from './protocol.gen.mjs';",
  '',
  'const COMMAND_SET = new Set(WORKER_COMMANDS);',
  'const EVENT_SET = new Set(WORKER_EVENTS);',
  '',
  'function assertRequiredFields(label, payload, required) {',
  '  if (!required || !required.length) return;',
  '  const missing = [];',
  '  for (const key of required) {',
  '    if (!Object.prototype.hasOwnProperty.call(payload, key)) missing.push(key);',
  '  }',
  '  if (missing.length) {',
  "    throw new Error(`${label} missing fields: ${missing.join(', ')}`);",
  '  }',
  '}',
  '',
  'export function encodeCommand(cmd, payload = {}) {',
  '  if (!COMMAND_SET.has(cmd)) throw new Error(`Unknown command: ${String(cmd)}`);',
  "  const body = payload && typeof payload === 'object' ? payload : {};",
  '  assertRequiredFields(`Command ${cmd}`, body, COMMAND_FIELDS[cmd]?.required || []);',
  '  return { cmd, ...body };',
  '}',
  '',
  'export function decodeCommand(message) {',
  "  if (!message || typeof message !== 'object') throw new Error('Command message must be an object.');",
  '  const cmd = message.cmd;',
  '  if (!COMMAND_SET.has(cmd)) throw new Error(`Unknown command: ${String(cmd)}`);',
  '  const payload = { ...message };',
  '  delete payload.cmd;',
  '  return { cmd, payload };',
  '}',
  '',
  'export function dispatchCommand(handlers, message) {',
  '  const decoded = decodeCommand(message);',
  '  assertRequiredFields(`Command ${decoded.cmd}`, decoded.payload, COMMAND_FIELDS[decoded.cmd]?.required || []);',
  '  const handler = handlers?.[decoded.cmd];',
  '  if (typeof handler !== "function") throw new Error(`Unhandled command: ${decoded.cmd}`);',
  '  return handler(decoded.payload, message);',
  '}',
  '',
  'export function encodeEvent(kind, payload = {}) {',
  '  if (!EVENT_SET.has(kind)) throw new Error(`Unknown event: ${String(kind)}`);',
  "  const body = payload && typeof payload === 'object' ? payload : {};",
  '  assertRequiredFields(`Event ${kind}`, body, EVENT_FIELDS[kind]?.required || []);',
  '  return { kind, ...body };',
  '}',
  '',
  'export function decodeEvent(message) {',
  "  if (!message || typeof message !== 'object') throw new Error('Event message must be an object.');",
  '  const kind = message.kind;',
  '  if (!EVENT_SET.has(kind)) throw new Error(`Unknown event: ${String(kind)}`);',
  '  const payload = { ...message };',
  '  delete payload.kind;',
  '  return { kind, payload };',
  '}',
  '',
  'export function dispatchEvent(handlers, message) {',
  '  const decoded = decodeEvent(message);',
  '  assertRequiredFields(`Event ${decoded.kind}`, decoded.payload, EVENT_FIELDS[decoded.kind]?.required || []);',
  '  const handler = handlers?.[decoded.kind];',
  '  if (typeof handler !== "function") throw new Error(`Unhandled event: ${decoded.kind}`);',
  '  return handler(decoded.payload, message);',
  '}',
  '',
].join('\n');

await mkdir(outDir, { recursive: true });
await writeFile(protocolOutPath, protocolOutput, 'utf8');
await writeFile(dispatchOutPath, dispatchOutput, 'utf8');
console.log(`Wrote ${protocolOutPath}`);
console.log(`Wrote ${dispatchOutPath}`);
